# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 281ba9e0bd13d91b79fe4a610614b541fcb3768b90807918f2484bffba692b3596fa7ee19a623451e70597312a0235fa28643d2686de1a85581a5ec4e33cf0cc

test:
  secret_key_base: 28c0ecf93049e7b3a722fecec6e4bbdd7de6d6f6672b0616c8d26486882d57cd77852942fe462a82cac1a589a9fce949fa15e16caaa7dd34ae257ffa01105a58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
